spring:
  config:
    import: optional:file:.env[.properties],optional:file:backend/.env[.properties]
  profiles:
    active: dev # par defaut en local

  mail:
    host: ${SPRING_MAIL_HOST:}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${SPRING_MAIL_SMTP_AUTH:true}
      mail.smtp.starttls.enable: ${SPRING_MAIL_SMTP_STARTTLS:true}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [openid, profile, email]

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me-dev-secret-change-me}
    expiration-minutes: 60

  oauth2:
    success-redirect: ${OAUTH2_SUCCESS_REDIRECT:http://localhost:5173/auth/callback}

  frontend:
    reset-password-url: ${APP_FRONTEND_RESET_PASSWORD_URL:http://localhost:5173/reset-password}

  password-reset:
    expiration-minutes: ${APP_PASSWORD_RESET_EXP_MINUTES:60}
    mail-from: ${APP_MAIL_FROM:}

---

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5433/snkProjet_docker}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:Pipounet29}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG
    backend.security: DEBUG

---

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  forward-headers-strategy: framework
